# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec9ce5aef6d312e76fce0284c7fe3224c2830910e7cc362145d2056cb1f478a61c59435efac130968fd98d3175cf9156ea1d9e89abae0d693cdd0ed9c0e743b0

test:
  secret_key_base: 497140f2f62bc1bd63974c0d824b8f671392ab7a90e0bd8d546db3f137c4bf3c3dee46b7d175f7445c446fb840040f8330bf1565dd49235067eadd522e8781bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
